import { RewardType, RewardCategory, RewardRarity, AchievementRarity, AchievementCategory } from '@prisma/client';
import { prisma } from './prisma';

/**
 * Seed example rewards for reward shop
 */
export async function seedRewards(householdId: string) {
  console.log('🎁 Seeding rewards...');

  const rewards = [
    // COMMON - Cosmetic
    {
      name: '🎨 Kolorowy Avatar',
      description: 'Zmień kolor swojego avatara na dowolny',
      icon: '🎨',
      pointsCost: 100,
      type: RewardType.COSMETIC,
      category: RewardCategory.AVATAR,
      rarity: RewardRarity.COMMON,
      householdId,
    },
    {
      name: '⭐ Prosta Odznaka',
      description: 'Dodaj prostą odznakę do swojego profilu',
      icon: '⭐',
      pointsCost: 150,
      type: RewardType.COSMETIC,
      category: RewardCategory.BADGE,
      rarity: RewardRarity.COMMON,
      householdId,
    },
    {
      name: '🎭 Emoji Pack #1',
      description: 'Odblokuj nowe emotikony do użycia',
      icon: '🎭',
      pointsCost: 200,
      type: RewardType.COSMETIC,
      category: RewardCategory.BADGE,
      rarity: RewardRarity.COMMON,
      householdId,
    },
    {
      name: '🌈 Tęczowy Pasek',
      description: 'Zmień pasek XP na kolorowy',
      icon: '🌈',
      pointsCost: 250,
      type: RewardType.COSMETIC,
      category: RewardCategory.THEME,
      rarity: RewardRarity.COMMON,
      householdId,
    },

    // RARE - Functional
    {
      name: '⚡ Bonus XP na 24h',
      description: '+25% XP przez 24 godziny',
      icon: '⚡',
      pointsCost: 500,
      type: RewardType.FUNCTIONAL,
      category: RewardCategory.PERK,
      rarity: RewardRarity.RARE,
      effectData: { type: 'xp_boost', multiplier: 1.25, duration: 86400 },
      householdId,
    },
    {
      name: '🛡️ Tarcza Streaku',
      description: 'Ochrona przed utratą streaku na 1 dzień',
      icon: '🛡️',
      pointsCost: 750,
      type: RewardType.FUNCTIONAL,
      category: RewardCategory.PERK,
      rarity: RewardRarity.RARE,
      effectData: { type: 'streak_shield', uses: 1 },
      householdId,
    },
    {
      name: '👑 Tytuł "Mistrz Zadań"',
      description: 'Dodaj tytuł pod swoją nazwą',
      icon: '👑',
      pointsCost: 800,
      type: RewardType.COSMETIC,
      category: RewardCategory.TITLE,
      rarity: RewardRarity.RARE,
      effectData: { titleId: 'task_master' },
      householdId,
    },
    {
      name: '🔥 Double XP na 1h',
      description: 'Podwojone XP przez godzinę',
      icon: '🔥',
      pointsCost: 600,
      type: RewardType.FUNCTIONAL,
      category: RewardCategory.PERK,
      rarity: RewardRarity.RARE,
      effectData: { type: 'xp_boost', multiplier: 2, duration: 3600 },
      householdId,
    },
    {
      name: '🎯 Priorytety VIP',
      description: 'Twoje zadania na górze listy przez 24h',
      icon: '🎯',
      pointsCost: 400,
      type: RewardType.FUNCTIONAL,
      category: RewardCategory.PERK,
      rarity: RewardRarity.RARE,
      effectData: { type: 'priority_boost', duration: 86400 },
      householdId,
    },
    {
      name: '💫 Animowane Tło',
      description: 'Odblokuj animowane tło dla profilu',
      icon: '💫',
      pointsCost: 900,
      type: RewardType.COSMETIC,
      category: RewardCategory.THEME,
      rarity: RewardRarity.RARE,
      effectData: { themeId: 'ocean' },
      householdId,
    },

    // EPIC - Exclusive
    {
      name: '💎 Motyw Premium',
      description: 'Odblokuj ekskluzywny motyw interfejsu',
      icon: '💎',
      pointsCost: 1500,
      type: RewardType.EXCLUSIVE,
      category: RewardCategory.THEME,
      rarity: RewardRarity.EPIC,
      requiredLevel: 10,
      effectData: { themeId: 'golden' },
      householdId,
    },
    {
      name: '🎬 Wybór Filmu',
      description: 'Wybierz film na wieczór dla całej rodziny',
      icon: '🎬',
      pointsCost: 2000,
      type: RewardType.PHYSICAL,
      category: RewardCategory.PHYSICAL,
      rarity: RewardRarity.EPIC,
      stock: 2,
      householdId,
    },
    {
      name: '🍕 Wybór Posiłku',
      description: 'Zdecyduj co będzie na obiad',
      icon: '🍕',
      pointsCost: 1800,
      type: RewardType.PHYSICAL,
      category: RewardCategory.PHYSICAL,
      rarity: RewardRarity.EPIC,
      stock: 3,
      householdId,
    },
    {
      name: '🎮 Wieczór Gamingowy',
      description: 'Dodatkowe 2h czasu na gry',
      icon: '🎮',
      pointsCost: 1200,
      type: RewardType.PHYSICAL,
      category: RewardCategory.PHYSICAL,
      rarity: RewardRarity.EPIC,
      stock: 4,
      householdId,
    },
    {
      name: '☕ Premium Kawa/Herbata',
      description: 'Wybierz premium napój do kupienia',
      icon: '☕',
      pointsCost: 1000,
      type: RewardType.PHYSICAL,
      category: RewardCategory.PHYSICAL,
      rarity: RewardRarity.EPIC,
      stock: 5,
      householdId,
    },
    {
      name: '🎨 Custom Avatar Design',
      description: 'Zaprojektuj własny unikalny avatar',
      icon: '🎨',
      pointsCost: 2500,
      type: RewardType.EXCLUSIVE,
      category: RewardCategory.AVATAR,
      rarity: RewardRarity.EPIC,
      requiredLevel: 15,
      householdId,
    },

    // LEGENDARY - Ultra Rare
    {
      name: '👑 Tytuł "Legenda"',
      description: 'Prestiżowy tytuł dla najlepszych',
      icon: '👑',
      pointsCost: 5000,
      type: RewardType.EXCLUSIVE,
      category: RewardCategory.TITLE,
      rarity: RewardRarity.LEGENDARY,
      requiredLevel: 20,
      effectData: { titleId: 'eternal_warrior' },
      householdId,
    },
    {
      name: '🎁 Dzień bez obowiązków',
      description: 'Dzień wolny od zadań domowych',
      icon: '🎁',
      pointsCost: 10000,
      type: RewardType.PHYSICAL,
      category: RewardCategory.PHYSICAL,
      rarity: RewardRarity.LEGENDARY,
      stock: 1,
      requiredLevel: 15,
      householdId,
    },
    {
      name: '🏆 Złoty Status',
      description: 'Permanentny +10% XP i ekskluzywna odznaka',
      icon: '🏆',
      pointsCost: 15000,
      type: RewardType.EXCLUSIVE,
      category: RewardCategory.PERK,
      rarity: RewardRarity.LEGENDARY,
      requiredLevel: 25,
      effectData: { type: 'permanent_xp_boost', multiplier: 1.1 },
      householdId,
    },
    {
      name: '🌟 VIP na miesiąc',
      description: 'Wszystkie perki aktywne przez miesiąc',
      icon: '🌟',
      pointsCost: 20000,
      type: RewardType.EXCLUSIVE,
      category: RewardCategory.PERK,
      rarity: RewardRarity.LEGENDARY,
      requiredLevel: 30,
      effectData: { type: 'vip_status', duration: 2592000 }, // 30 dni
      householdId,
    },

    // SEASONAL
    {
      name: '🎄 Świąteczny Avatar',
      description: 'Limitowany świąteczny avatar',
      icon: '🎄',
      pointsCost: 1000,
      type: RewardType.COSMETIC,
      category: RewardCategory.AVATAR,
      rarity: RewardRarity.RARE,
      isSeasonal: true,
      seasonName: 'Święta 2026',
      availableFrom: new Date('2026-12-01'),
      availableUntil: new Date('2026-12-31'),
      householdId,
    },
    {
      name: '🎃 Halloween Pack',
      description: 'Straszne ozdoby na Halloween',
      icon: '🎃',
      pointsCost: 800,
      type: RewardType.COSMETIC,
      category: RewardCategory.THEME,
      rarity: RewardRarity.RARE,
      isSeasonal: true,
      seasonName: 'Halloween 2026',
      availableFrom: new Date('2026-10-20'),
      availableUntil: new Date('2026-11-01'),
      effectData: { themeId: 'midnight' },
      householdId,
    },
    {
      name: '🌸 Wiosenny Motyw',
      description: 'Pastelowe kolory na wiosnę',
      icon: '🌸',
      pointsCost: 600,
      type: RewardType.COSMETIC,
      category: RewardCategory.THEME,
      rarity: RewardRarity.COMMON,
      isSeasonal: true,
      seasonName: 'Wiosna 2026',
      availableFrom: new Date('2026-03-20'),
      availableUntil: new Date('2026-06-21'),
      effectData: { themeId: 'lavender' },
      householdId,
    },

    // EXPANDED THEMES - All 8 reward themes
    {
      name: '🌊 Motyw Ocean',
      description: 'Spokojny niebieski motyw inspirowany oceanem',
      icon: '🌊',
      pointsCost: 1200,
      type: RewardType.COSMETIC,
      category: RewardCategory.THEME,
      rarity: RewardRarity.RARE,
      effectData: { themeId: 'ocean' },
      householdId,
    },
    {
      name: '🌲 Motyw Las',
      description: 'Naturalny zielony motyw lasu',
      icon: '🌲',
      pointsCost: 1200,
      type: RewardType.COSMETIC,
      category: RewardCategory.THEME,
      rarity: RewardRarity.RARE,
      effectData: { themeId: 'forest' },
      householdId,
    },
    {
      name: '🌅 Motyw Zachód Słońca',
      description: 'Ciepły motyw z kolorami zachodu słońca',
      icon: '🌅',
      pointsCost: 1500,
      type: RewardType.COSMETIC,
      category: RewardCategory.THEME,
      rarity: RewardRarity.EPIC,
      effectData: { themeId: 'sunset' },
      householdId,
    },
    {
      name: '✨ Motyw Magiczny',
      description: 'Magiczny fioletowy motyw',
      icon: '✨',
      pointsCost: 1800,
      type: RewardType.COSMETIC,
      category: RewardCategory.THEME,
      rarity: RewardRarity.EPIC,
      requiredLevel: 10,
      effectData: { themeId: 'lavender' },
      householdId,
    },
    {
      name: '🎮 Motyw Cyberpunk',
      description: 'Futurystyczny motyw z neonowymi kolorami',
      icon: '🎮',
      pointsCost: 2500,
      type: RewardType.EXCLUSIVE,
      category: RewardCategory.THEME,
      rarity: RewardRarity.LEGENDARY,
      requiredLevel: 15,
      effectData: { themeId: 'golden' },
      householdId,
    },
    {
      name: '🌸 Motyw Wiśnia',
      description: 'Delikatny różowy motyw kwiatu wiśni',
      icon: '🌸',
      pointsCost: 1500,
      type: RewardType.COSMETIC,
      category: RewardCategory.THEME,
      rarity: RewardRarity.EPIC,
      effectData: { themeId: 'cherry' },
      householdId,
    },
    {
      name: '🌙 Motyw Północ',
      description: 'Ciemny motyw z niebieskimi akcentami',
      icon: '🌙',
      pointsCost: 2000,
      type: RewardType.COSMETIC,
      category: RewardCategory.THEME,
      rarity: RewardRarity.EPIC,
      requiredLevel: 10,
      effectData: { themeId: 'midnight' },
      householdId,
    },

    // EXPANDED TITLES
    {
      name: '🏆 Tytuł "Mistrz Kuchni"',
      description: 'Dla mistrzów kulinarnych sztuk',
      icon: '🏆',
      pointsCost: 1500,
      type: RewardType.COSMETIC,
      category: RewardCategory.TITLE,
      rarity: RewardRarity.EPIC,
      requiredLevel: 10,
      effectData: { titleId: 'master_chef' },
      householdId,
    },
    {
      name: '🧹 Tytuł "Król Porządku"',
      description: 'Dla perfekcjonistów czystości',
      icon: '🧹',
      pointsCost: 1500,
      type: RewardType.COSMETIC,
      category: RewardCategory.TITLE,
      rarity: RewardRarity.EPIC,
      requiredLevel: 10,
      effectData: { titleId: 'consistency_king' },
      householdId,
    },
    {
      name: '💪 Tytuł "Champion"',
      description: 'Mistrz wszystkich kategorii',
      icon: '💪',
      pointsCost: 3000,
      type: RewardType.EXCLUSIVE,
      category: RewardCategory.TITLE,
      rarity: RewardRarity.LEGENDARY,
      requiredLevel: 20,
      effectData: { titleId: 'grandmaster' },
      householdId,
    },
    {
      name: '⭐ Tytuł "Guru Gospodarstwa"',
      description: 'Najwyższy tytuł w gospodarstwie',
      icon: '⭐',
      pointsCost: 5000,
      type: RewardType.EXCLUSIVE,
      category: RewardCategory.TITLE,
      rarity: RewardRarity.LEGENDARY,
      requiredLevel: 25,
      effectData: { titleId: 'founder' },
      householdId,
    },

    // EXPANDED XP BOOSTS
    {
      name: '⚡ XP Boost x1.5 na 3 dni',
      description: '+50% XP przez 3 dni',
      icon: '⚡',
      pointsCost: 2000,
      type: RewardType.FUNCTIONAL,
      category: RewardCategory.PERK,
      rarity: RewardRarity.EPIC,
      effectData: { type: 'xp_boost', multiplier: 1.5, duration: 259200 },
      householdId,
    },
    {
      name: '🚀 Mega XP Boost x3 na 30min',
      description: 'Potężny boost na krótki czas',
      icon: '🚀',
      pointsCost: 1000,
      type: RewardType.FUNCTIONAL,
      category: RewardCategory.PERK,
      rarity: RewardRarity.RARE,
      effectData: { type: 'xp_boost', multiplier: 3, duration: 1800 },
      householdId,
    },
    {
      name: '💫 Weekend Boost x2',
      description: 'Podwojone XP przez cały weekend',
      icon: '💫',
      pointsCost: 3000,
      type: RewardType.FUNCTIONAL,
      category: RewardCategory.PERK,
      rarity: RewardRarity.EPIC,
      effectData: { type: 'xp_boost', multiplier: 2, duration: 172800 },
      householdId,
    },

    // EXPANDED PHYSICAL REWARDS
    {
      name: '🍰 Ulubiony Deser',
      description: 'Wybierz swój ulubiony deser',
      icon: '🍰',
      pointsCost: 600,
      type: RewardType.PHYSICAL,
      category: RewardCategory.PHYSICAL,
      rarity: RewardRarity.RARE,
      stock: 4,
      householdId,
    },
    {
      name: '🍔 Fast Food Day',
      description: 'Dzień z fast foodem',
      icon: '🍔',
      pointsCost: 800,
      type: RewardType.PHYSICAL,
      category: RewardCategory.PHYSICAL,
      rarity: RewardRarity.RARE,
      stock: 3,
      householdId,
    },
    {
      name: '💤 Dodatkowa godzina snu',
      description: 'Śpij godzinę dłużej bez konsekwencji',
      icon: '💤',
      pointsCost: 500,
      type: RewardType.PHYSICAL,
      category: RewardCategory.PHYSICAL,
      rarity: RewardRarity.RARE,
      stock: 7,
      householdId,
    },
    {
      name: '🎵 Wybór Playlisty',
      description: 'Kontroluj muzykę przez cały dzień',
      icon: '🎵',
      pointsCost: 800,
      type: RewardType.PHYSICAL,
      category: RewardCategory.PHYSICAL,
      rarity: RewardRarity.RARE,
      stock: 5,
      householdId,
    },
    {
      name: '🚫 Pomiń jedno zadanie',
      description: 'Pomiń dowolne zadanie bez utraty punktów',
      icon: '🚫',
      pointsCost: 1500,
      type: RewardType.PHYSICAL,
      category: RewardCategory.PHYSICAL,
      rarity: RewardRarity.EPIC,
      stock: 2,
      householdId,
    },
  ];

  for (const reward of rewards) {
    await prisma.reward.upsert({
      where: {
        // Unique constraint by name and household
        householdId_name: {
          householdId: reward.householdId,
          name: reward.name,
        },
      },
      update: reward,
      create: reward,
    });
  }

  console.log(`✅ Seeded ${rewards.length} rewards!`);
}

/**
 * Seed enhanced achievements with hints and rarity
 */
export async function seedEnhancedAchievements() {
  console.log('🏆 Seeding enhanced achievements...');

  const achievements = [
    // COMMON - Starter achievements
    {
      name: 'Pierwsze Kroki',
      description: 'Ukończ swoje pierwsze zadanie',
      icon: '👣',
      category: AchievementCategory.TASKS,
      requirementType: 'TASKS_COMPLETED',
      requirementValue: 1,
      xpReward: 10,
      rarity: AchievementRarity.COMMON,
      hint: 'Ukończ dowolne zadanie aby odblokować',
      showProgressBar: true,
    },
    {
      name: 'Debiutant Kucharza',
      description: 'Stwórz swój pierwszy przepis',
      icon: '🍳',
      category: AchievementCategory.RECIPES,
      requirementType: 'RECIPES_CREATED',
      requirementValue: 1,
      xpReward: 15,
      rarity: AchievementRarity.COMMON,
      hint: 'Dodaj przepis w sekcji Przepisy',
      detailedHint: 'Wejdź w zakładkę Przepisy i kliknij "Dodaj Przepis"',
      showProgressBar: true,
    },

    // RARE - Mid-tier achievements
    {
      name: 'Pracuś',
      description: 'Ukończ 50 zadań',
      icon: '💪',
      category: AchievementCategory.TASKS,
      requirementType: 'TASKS_COMPLETED',
      requirementValue: 50,
      xpReward: 100,
      rarity: AchievementRarity.RARE,
      hint: 'Ukończ łącznie 50 zadań',
      showProgressBar: true,
      tierName: 'Bronze',
      tier: 1,
      seriesName: 'Mistrz Zadań',
    },
    {
      name: 'Gotowy na wszystko',
      description: 'Ukończ 7-dniową serię zadań',
      icon: '🔥',
      category: AchievementCategory.STREAK,
      requirementType: 'STREAK_DAYS',
      requirementValue: 7,
      xpReward: 150,
      rarity: AchievementRarity.RARE,
      hint: 'Zaloguj się i ukończ zadania przez 7 dni z rzędu',
      detailedHint: 'Pamiętaj aby każdego dnia ukończyć przynajmniej jedno zadanie',
      showProgressBar: true,
      badgeUnlock: '🔥 Ognista Seria',
    },

    // EPIC - Hard achievements
    {
      name: 'Mistrz Zadań',
      description: 'Ukończ 200 zadań',
      icon: '👑',
      category: AchievementCategory.TASKS,
      requirementType: 'TASKS_COMPLETED',
      requirementValue: 200,
      xpReward: 500,
      rarity: AchievementRarity.EPIC,
      hint: 'Ukończ łącznie 200 zadań',
      showProgressBar: true,
      tierName: 'Silver',
      tier: 2,
      seriesName: 'Mistrz Zadań',
      titleUnlock: 'Mistrz Zadań',
    },
    {
      name: 'Kucharz Gwiazd',
      description: 'Stwórz 25 przepisów',
      icon: '⭐',
      category: AchievementCategory.RECIPES,
      requirementType: 'RECIPES_CREATED',
      requirementValue: 25,
      xpReward: 400,
      rarity: AchievementRarity.EPIC,
      hint: 'Stwórz 25 unikalnych przepisów',
      detailedHint: 'Eksperymentuj z różnymi daniami i dodawaj je do bazy',
      showProgressBar: true,
      badgeUnlock: '⭐ Gwiazdka Michelin',
    },

    // LEGENDARY - Ultra rare
    {
      name: 'Legenda',
      description: 'Ukończ 1000 zadań',
      icon: '💎',
      category: AchievementCategory.TASKS,
      requirementType: 'TASKS_COMPLETED',
      requirementValue: 1000,
      xpReward: 2000,
      rarity: AchievementRarity.LEGENDARY,
      hint: 'Tylko dla najbardziej wytrwałych',
      detailedHint: 'To osiągnięcie wymaga czasu i konsekwencji. Ukończ 1000 zadań!',
      showProgressBar: true,
      tierName: 'Platinum',
      tier: 4,
      seriesName: 'Mistrz Zadań',
      titleUnlock: 'Legenda',
      badgeUnlock: '💎 Diamentowa Legenda',
    },
    {
      name: 'Niezniszczalny',
      description: 'Utrzymaj 30-dniową serię',
      icon: '🛡️',
      category: AchievementCategory.STREAK,
      requirementType: 'STREAK_DAYS',
      requirementValue: 30,
      xpReward: 1000,
      rarity: AchievementRarity.LEGENDARY,
      hint: 'Zaloguj się i ukończ zadania przez 30 dni z rzędu',
      detailedHint: 'Najdłuższe wyzwanie - bez przerwy przez cały miesiąc!',
      showProgressBar: true,
      titleUnlock: 'Niezniszczalny',
      badgeUnlock: '🛡️ Stalowa Tarcza',
    },

    // MEALS - Meal planning achievements
    {
      name: 'Planowanie Posiłków - Start',
      description: 'Zaplanuj swój pierwszy posiłek',
      icon: '🍽️',
      category: AchievementCategory.MEALS,
      requirementType: 'MEALS_PLANNED',
      requirementValue: 1,
      xpReward: 10,
      rarity: AchievementRarity.COMMON,
      hint: 'Użyj kalendarza posiłków aby zaplanować pierwszy obiad',
      showProgressBar: true,
    },
    {
      name: 'Mistrz Planowania',
      description: 'Zaplanuj posiłki na cały tydzień',
      icon: '📅',
      category: AchievementCategory.MEALS,
      requirementType: 'WEEKLY_MEAL_PLAN',
      requirementValue: 7,
      xpReward: 200,
      rarity: AchievementRarity.RARE,
      hint: 'Zaplanuj 7 posiłków w jednym tygodniu',
      detailedHint: 'Otwórz planer posiłków i zaplanuj każdy dzień tygodnia',
      showProgressBar: true,
    },
    {
      name: 'Zdrowe Nawyki',
      description: 'Zaplanuj 100 zdrowych posiłków',
      icon: '🥗',
      category: AchievementCategory.MEALS,
      requirementType: 'MEALS_PLANNED',
      requirementValue: 100,
      xpReward: 400,
      rarity: AchievementRarity.EPIC,
      hint: 'Planuj regularnie zdrowe posiłki',
      showProgressBar: true,
      tierName: 'Gold',
      tier: 3,
      seriesName: 'Mistrz Posiłków',
    },

    // SHOPPING - Shopping list achievements
    {
      name: 'Pierwsza Lista',
      description: 'Stwórz pierwszą listę zakupów',
      icon: '🛒',
      category: AchievementCategory.SHOPPING,
      requirementType: 'SHOPPING_LISTS_CREATED',
      requirementValue: 1,
      xpReward: 10,
      rarity: AchievementRarity.COMMON,
      hint: 'Utwórz listę zakupów w aplikacji',
      showProgressBar: true,
    },
    {
      name: 'Zakupoholik',
      description: 'Ukończ 20 list zakupów',
      icon: '🛍️',
      category: AchievementCategory.SHOPPING,
      requirementType: 'SHOPPING_LISTS_COMPLETED',
      requirementValue: 20,
      xpReward: 150,
      rarity: AchievementRarity.RARE,
      hint: 'Zrealizuj 20 list zakupów',
      detailedHint: 'Oznacz wszystkie produkty jako kupione na 20 listach',
      showProgressBar: true,
      tier: 1,
      tierName: 'Bronze',
      seriesName: 'Mistrz Zakupów',
    },
    {
      name: 'Ekonomiczny Geniusz',
      description: 'Zaoszczędź 1000 zł na zakupach',
      icon: '💰',
      category: AchievementCategory.SHOPPING,
      requirementType: 'MONEY_SAVED',
      requirementValue: 1000,
      xpReward: 500,
      rarity: AchievementRarity.EPIC,
      hint: 'Kupuj produkty w promocji i porównuj ceny',
      detailedHint: 'Używaj porównania cen i kupuj w promocjach',
      showProgressBar: true,
      titleUnlock: 'Ekonomiczny Geniusz',
    },

    // INVENTORY - Inventory management achievements
    {
      name: 'Zorganizowany Start',
      description: 'Dodaj pierwsze produkty do inwentarza',
      icon: '📦',
      category: AchievementCategory.INVENTORY,
      requirementType: 'INVENTORY_ITEMS_ADDED',
      requirementValue: 5,
      xpReward: 15,
      rarity: AchievementRarity.COMMON,
      hint: 'Dodaj 5 produktów do swojego inwentarza',
      showProgressBar: true,
    },
    {
      name: 'Strażnik Zapasów',
      description: 'Zarządzaj 50 produktami w inwentarzu',
      icon: '🏪',
      category: AchievementCategory.INVENTORY,
      requirementType: 'INVENTORY_ITEMS_MANAGED',
      requirementValue: 50,
      xpReward: 200,
      rarity: AchievementRarity.RARE,
      hint: 'Dodaj i zarządzaj 50 różnymi produktami',
      detailedHint: 'Regularnie aktualizuj stan swoich zapasów',
      showProgressBar: true,
      badgeUnlock: '🏪 Magazynier',
    },
    {
      name: 'Zero Marnotrawstwa',
      description: 'Nie zmarnuj żadnego produktu przez miesiąc',
      icon: '♻️',
      category: AchievementCategory.INVENTORY,
      requirementType: 'ZERO_WASTE_DAYS',
      requirementValue: 30,
      xpReward: 600,
      rarity: AchievementRarity.EPIC,
      hint: 'Użyj wszystkich produktów przed ich wygaśnięciem',
      detailedHint: 'Śledź daty ważności i planuj posiłki bazując na zapasach',
      showProgressBar: true,
      titleUnlock: 'Eko Wojownik',
      badgeUnlock: '♻️ Strażnik Planety',
    },

    // SOCIAL - Household collaboration achievements
    {
      name: 'Pierwsza Współpraca',
      description: 'Ukończ zadanie przypisane przez innego członka',
      icon: '🤝',
      category: AchievementCategory.SOCIAL,
      requirementType: 'TASKS_FROM_OTHERS_COMPLETED',
      requirementValue: 1,
      xpReward: 20,
      rarity: AchievementRarity.COMMON,
      hint: 'Ukończ zadanie które ktoś Ci przypisał',
      showProgressBar: true,
    },
    {
      name: 'Gracz Zespołowy',
      description: 'Współpracuj z innymi - 50 zadań zespołowych',
      icon: '👥',
      category: AchievementCategory.SOCIAL,
      requirementType: 'COLLABORATIVE_TASKS',
      requirementValue: 50,
      xpReward: 250,
      rarity: AchievementRarity.RARE,
      hint: 'Pracuj razem z gospodarstwem domowym',
      detailedHint: 'Ukończ 50 zadań współdzielonych lub przypisanych przez innych',
      showProgressBar: true,
      tier: 1,
      tierName: 'Bronze',
      seriesName: 'Mistrz Współpracy',
    },
    {
      name: 'Lider Gospodarstwa',
      description: 'Przypisz i monitoruj 100 zadań dla innych',
      icon: '👑',
      category: AchievementCategory.SOCIAL,
      requirementType: 'TASKS_ASSIGNED_TO_OTHERS',
      requirementValue: 100,
      xpReward: 400,
      rarity: AchievementRarity.EPIC,
      hint: 'Organizuj pracę w gospodarstwie domowym',
      detailedHint: 'Deleguj zadania i wspieraj innych członków rodziny',
      showProgressBar: true,
      titleUnlock: 'Lider',
      badgeUnlock: '👑 Korona Lidera',
    },

    // MASTER - Cross-category mastery
    {
      name: 'Wszechstronny',
      description: 'Zdobądź po jednym osiągnięciu w każdej kategorii',
      icon: '🌟',
      category: AchievementCategory.MASTER,
      requirementType: 'ALL_CATEGORIES',
      requirementValue: 1,
      xpReward: 300,
      rarity: AchievementRarity.RARE,
      hint: 'Spróbuj wszystkich funkcji aplikacji',
      detailedHint: 'Zdobądź przynajmniej jedno osiągnięcie w: zadaniach, przepisach, posiłkach, zakupach, inwentarzu i współpracy',
      showProgressBar: true,
      badgeUnlock: '🌟 Wszechstronność',
    },
    {
      name: 'Perfekcjonista',
      description: 'Zdobądź 50 różnych osiągnięć',
      icon: '💯',
      category: AchievementCategory.MASTER,
      requirementType: 'ACHIEVEMENTS_UNLOCKED',
      requirementValue: 50,
      xpReward: 1000,
      rarity: AchievementRarity.EPIC,
      hint: 'Zbieraj osiągnięcia ze wszystkich kategorii',
      showProgressBar: true,
      titleUnlock: 'Perfekcjonista',
    },
    {
      name: 'Absolutny Mistrz',
      description: 'Osiągnij 100 poziom i zdobądź wszystkie osiągnięcia',
      icon: '🏆',
      category: AchievementCategory.MASTER,
      requirementType: 'LEVEL_AND_ALL_ACHIEVEMENTS',
      requirementValue: 100,
      xpReward: 5000,
      rarity: AchievementRarity.LEGENDARY,
      hint: 'Najwyższe wyróżnienie - tylko dla prawdziwych mistrzów',
      detailedHint: 'Osiągnij poziom 100 i zdobądź wszystkie dostępne osiągnięcia',
      showProgressBar: true,
      titleUnlock: 'Absolutny Mistrz',
      badgeUnlock: '🏆 Złoty Graal',
    },

    // SECRET achievements
    {
      name: '???',
      description: '???',
      icon: '❓',
      category: AchievementCategory.MASTER,
      requirementType: 'SECRET_CONDITION',
      requirementValue: 1,
      xpReward: 500,
      isSecret: true,
      rarity: AchievementRarity.EPIC,
      hint: 'Ukryte osiągnięcie - odkryj je samodzielnie!',
      showProgressBar: false,
    },
    {
      name: 'Nocny Marek',
      description: 'Ukończ zadanie o 3:00 w nocy',
      icon: '🦉',
      category: AchievementCategory.TASKS,
      requirementType: 'TASK_AT_NIGHT',
      requirementValue: 1,
      xpReward: 100,
      isSecret: true,
      rarity: AchievementRarity.RARE,
      hint: 'Coś związanego z nocą...',
      showProgressBar: false,
    },
    {
      name: 'Speed Runner',
      description: 'Ukończ 10 zadań w ciągu 10 minut',
      icon: '⚡',
      category: AchievementCategory.TASKS,
      requirementType: 'SPEED_COMPLETION',
      requirementValue: 10,
      xpReward: 200,
      isSecret: true,
      rarity: AchievementRarity.EPIC,
      hint: 'Prędkość to twoja supersiła',
      showProgressBar: false,
    },
  ];

  for (const achievement of achievements) {
    const { name, category, ...data } = achievement;
    await prisma.achievement.upsert({
      where: {
        name_category: {
          name,
          category,
        },
      },
      update: data,
      create: achievement,
    });
  }

  console.log(`✅ Seeded ${achievements.length} enhanced achievements!`);
}

